# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-12 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_work', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
