# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-31 07:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('org_work', '0002_projects_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='category',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='parent',
        ),
    ]
