# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-09 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_home', '0008_remove_categories_projects'),
        ('org_work', '0004_auto_20180409_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='category',
        ),
        migrations.AddField(
            model_name='projects',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='org_home.Categories'),
        ),
    ]
