# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-28 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_work', '0005_auto_20180409_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, related_name='relatedCategory', to='org_home.Categories'),
        ),
    ]
