# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-04 07:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('org_home', '0014_auto_20181019_0756'),
        ('org_work', '0008_worksubmissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worksubmissions',
            name='project',
        ),
        migrations.AddField(
            model_name='worksubmissions',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='org_home.Categories'),
        ),
    ]
