# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-04 07:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_systemofgovernance'),
        ('org_work', '0009_auto_20181104_0737'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksubmissions',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Organizations'),
        ),
    ]
