# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-04 09:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('org_work', '0011_auto_20181104_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksubmissions',
            name='poster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posterName', to=settings.AUTH_USER_MODEL),
        ),
    ]
