# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-21 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_work', '0012_worksubmissions_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksubmissions',
            name='accepted',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
