# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-05 00:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('closed_category', models.BooleanField()),
                ('gateKeeper', models.CharField(max_length=30)),
                ('members', models.ManyToManyField(related_name='member', to=settings.AUTH_USER_MODEL)),
                ('moderators', models.ManyToManyField(related_name='super_member', to=settings.AUTH_USER_MODEL)),
                ('pending_members', models.ManyToManyField(related_name='pending_member', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
