# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-05 05:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        ('org_home', '0002_categories_category_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Organizations'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='members',
            field=models.ManyToManyField(related_name='category_member', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='categories',
            name='moderators',
            field=models.ManyToManyField(related_name='category_super_member', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='categories',
            name='pending_members',
            field=models.ManyToManyField(related_name='category_pending_member', to=settings.AUTH_USER_MODEL),
        ),
    ]
