# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-21 03:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('org_home', '0004_auto_20180109_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='parentalModerators',
            field=models.ManyToManyField(related_name='category_parental_mod', to=settings.AUTH_USER_MODEL),
        ),
    ]
