# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-31 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_work', '0003_auto_20180331_0745'),
        ('org_home', '0005_categories_parentalmoderators'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='projects',
            field=models.ManyToManyField(blank=True, null=True, to='org_work.Projects'),
        ),
    ]
