# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-09 13:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('org_home', '0007_auto_20180331_0817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='projects',
        ),
    ]
