# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-28 08:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('org_home', '0008_remove_categories_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_parent', to='org_home.Categories'),
        ),
    ]
