# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-07-13 10:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('org_home', '0010_positions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='positions',
            old_name='position',
            new_name='position_name',
        ),
    ]
