# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-07-16 10:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('org_home', '0011_auto_20180713_1036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='positions',
            old_name='user',
            new_name='position_holders',
        ),
    ]
