# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-07-27 02:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('org_home', '0012_auto_20180716_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='positions',
            name='position_requesters',
            field=models.ManyToManyField(blank=True, null=True, related_name='position_requesters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='positions',
            name='position_holders',
            field=models.ManyToManyField(blank=True, null=True, related_name='position_holders', to=settings.AUTH_USER_MODEL),
        ),
    ]
