# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-21 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_home', '0014_auto_20181019_0756'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='needAcceptedContribs',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
