# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-08-15 04:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_discussion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discussion',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='discussion',
            name='question',
        ),
        migrations.RemoveField(
            model_name='discussion',
            name='user',
        ),
        migrations.RemoveField(
            model_name='discussion',
            name='userDownVotes',
        ),
        migrations.RemoveField(
            model_name='discussion',
            name='userUpVotes',
        ),
        migrations.DeleteModel(
            name='Discussion',
        ),
    ]
