# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-08-15 06:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discuss', '0005_remove_post_question'),
        ('vote', '0003_auto_20180815_0459'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='discuss.Post'),
        ),
    ]
