# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-08-21 03:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizations',
            name='description',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='organizations',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organizations',
            name='organization_type',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='organizations',
            name='gateKeeper',
            field=models.CharField(default='', max_length=30),
        ),
    ]
