# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-08-21 03:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20180821_0336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizations',
            name='closed_organization',
            field=models.BooleanField(default=False),
        ),
    ]
