# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-08-24 07:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('org_home', '0013_auto_20180727_0242'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0003_auto_20180821_0338'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnyMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('removingPoorQualityContributions', models.BooleanField(default=False)),
                ('finalProductDecisions', models.BooleanField(default=False)),
                ('acceptingOrRejectingContribs', models.BooleanField(default=False)),
                ('directionOfBusiness', models.BooleanField(default=False)),
                ('removingMember', models.BooleanField(default=False)),
                ('percentCommunityMustVote', models.BooleanField(default=False)),
                ('numberOfMods', models.BooleanField(default=False)),
                ('whoModsAre', models.BooleanField(default=False)),
                ('MonetaryDistr', models.BooleanField(default=False)),
                ('VotingSystem', models.BooleanField(default=False)),
                ('MemberJoining', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnyModOrRep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('removingPoorQualityContributions', models.BooleanField(default=True)),
                ('finalProductDecisions', models.BooleanField(default=True)),
                ('acceptingOrRejectingContribs', models.BooleanField(default=True)),
                ('directionOfBusiness', models.BooleanField(default=False)),
                ('removingMember', models.BooleanField(default=False)),
                ('percentCommunityMustVote', models.BooleanField(default=False)),
                ('numberOfMods', models.BooleanField(default=False)),
                ('whoModsAre', models.BooleanField(default=False)),
                ('MonetaryDistr', models.BooleanField(default=False)),
                ('VotingSystem', models.BooleanField(default=False)),
                ('MemberJoining', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MemberVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('removingPoorQualityContributions', models.BooleanField(default=False)),
                ('finalProductDecisions', models.BooleanField(default=False)),
                ('acceptingOrRejectingContribs', models.BooleanField(default=True)),
                ('directionOfBusiness', models.BooleanField(default=False)),
                ('removingMember', models.BooleanField(default=False)),
                ('percentCommunityMustVote', models.BooleanField(default=True)),
                ('numberOfMods', models.BooleanField(default=True)),
                ('whoModsAre', models.BooleanField(default=True)),
                ('MonetaryDistr', models.BooleanField(default=True)),
                ('VotingSystem', models.BooleanField(default=True)),
                ('MemberJoining', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ModOrRepVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('removingPoorQualityContributions', models.BooleanField(default=False)),
                ('finalProductDecisions', models.BooleanField(default=False)),
                ('acceptingOrRejectingContribs', models.BooleanField(default=False)),
                ('directionOfBusiness', models.BooleanField(default=True)),
                ('removingMember', models.BooleanField(default=True)),
                ('percentCommunityMustVote', models.BooleanField(default=False)),
                ('numberOfMods', models.BooleanField(default=False)),
                ('whoModsAre', models.BooleanField(default=False)),
                ('MonetaryDistr', models.BooleanField(default=False)),
                ('VotingSystem', models.BooleanField(default=False)),
                ('MemberJoining', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MonetaryDistribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InvestorsWorkersFounders', models.FloatField(default=80)),
                ('OrgBank', models.FloatField(default=14)),
                ('ServiceFee', models.FloatField(default=6)),
                ('sharesPerDollarInvested', models.FloatField(default=100)),
                ('sharesPerUpvoteOnForumPost', models.FloatField(default=0)),
                ('sharesPerUpvoteOnContribution', models.FloatField(default=10)),
                ('sharesPerAcceptedPostedIdea', models.FloatField(default=100)),
                ('sharesPerUsedContrib', models.FloatField(default=100)),
                ('numOriginalFounders', models.FloatField(default=10)),
                ('sharesPerFounderBonus', models.FloatField(default=100000)),
                ('sharesPerEachUseOfCode', models.FloatField(default=50)),
                ('sharesPerLineAcceptedCode', models.FloatField(default=100)),
                ('machineLearningShareDistr', models.BooleanField(default=False)),
                ('contributionSharesVotable', models.BooleanField(default=True)),
                ('numVoteForContrib', models.FloatField(default=30)),
                ('contribVoteLength', models.FloatField(default=0)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Organizations')),
            ],
        ),
        migrations.CreateModel(
            name='SystemOfGovernance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeFoGovernance', models.CharField(default='MixDeptRepsDirectDem', max_length=500)),
                ('votingType', models.CharField(blank=True, default='shareBased', max_length=500, null=True)),
                ('userRetainSharesAfterBanishment', models.BooleanField(default=True)),
                ('enableVestingPeriodNewMembers', models.BooleanField(default=False)),
                ('AnyMember', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.AnyMember')),
                ('AnyModOrRep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.AnyModOrRep')),
                ('MemberVote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.MemberVote')),
                ('ModOrRepVote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.ModOrRepVote')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='org_home.Categories')),
                ('founders', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Organizations')),
            ],
        ),
    ]
