# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-10-19 07:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('org_home', '0014_auto_20181019_0756'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0006_auto_20181019_0756'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemOfGovernance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeFoGovernance', models.CharField(default='MixDeptRepsDirectDem', max_length=500)),
                ('votingType', models.CharField(blank=True, default='shareBased', max_length=500, null=True)),
                ('votingLength', models.FloatField(default=172800)),
                ('doElectionsOccur', models.BooleanField(default=False)),
                ('frequencyOfElections', models.IntegerField(default=0)),
                ('maxNumberReElections', models.IntegerField(default=0)),
                ('minNumberMemberDays', models.IntegerField(default=0)),
                ('minNumberShares', models.IntegerField(default=0)),
                ('minNumberAcceptedContribs', models.IntegerField(default=0)),
                ('votedIn', models.BooleanField(default=False)),
                ('acceptedByAuthority', models.BooleanField(default=False)),
                ('userRetainSharesAfterBanishment', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='org_home.Categories')),
                ('departments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.DepartmentStack')),
                ('founders', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Organizations')),
            ],
        ),
    ]
