# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-24 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_systemofgovernance'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizations',
            name='contract_address',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
