# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-07-02 17:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('consensusEditing', '0002_auto_20180629_0205'),
    ]

    operations = [
        migrations.CreateModel(
            name='vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votes', models.IntegerField(default=0)),
                ('textDoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consensusEditing.TextDoc')),
                ('voters', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
