# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-21 03:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discuss', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reply',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
