# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-21 21:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('discuss', '0002_auto_20180221_0349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='score',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='score',
        ),
        migrations.AddField(
            model_name='post',
            name='userDownVotes',
            field=models.ManyToManyField(blank=True, related_name='PostDownVotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='userUpVotes',
            field=models.ManyToManyField(blank=True, related_name='PostUpVotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reply',
            name='userDownVotes',
            field=models.ManyToManyField(blank=True, related_name='RepliesDownVotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reply',
            name='userUpVotes',
            field=models.ManyToManyField(blank=True, related_name='RepliesUpVotes', to=settings.AUTH_USER_MODEL),
        ),
    ]
