# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-08-15 04:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0003_auto_20180815_0459'),
        ('discuss', '0003_auto_20180221_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vote.Question'),
        ),
    ]
