# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-08-15 06:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discuss', '0004_post_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='question',
        ),
    ]
