# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-07-28 19:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
        ('org_home', '0013_auto_20180727_0242'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(blank=True, null=True, verbose_name='date published')),
                ('activity_description', models.CharField(max_length=100)),
                ('link_to_change', models.URLField()),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='org_home.Categories')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Organizations')),
            ],
            options={
                'ordering': ['pub_date'],
            },
        ),
    ]
