# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-07-29 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_feed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitypost',
            name='link_to_change',
            field=models.CharField(max_length=500),
        ),
    ]
